# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Knox Devs
email: robert@knoxux.com
description: > # this means to ignore newlines until "baseurl:"
  Great Mountains. Great Devs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.knoxux.com" # the base hostname & protocol for your site
twitter_username: knox_ux
github_username:  KnoxUX

# Build settings
markdown: kramdown
